from django.db import models
from django.contrib.auth.models import User
from jd_parser.models import JobDescription

class GeneratedResume(models.Model):
    """Stores the resume content generated by the AI for a specific user and job description."""
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='generated_resumes')
    job_description = models.ForeignKey(JobDescription, on_delete=models.CASCADE, related_name='generated_resumes')
    generated_content = models.TextField(help_text="The actual resume content generated by the AI.")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Generated Resume for {self.user.username} (JD: {self.job_description.id}) - {self.created_at.strftime('%Y-%m-%d %H:%M')}"

    class Meta:
        ordering = ['-created_at']
