# Generated by Django 5.1.3 on 2025-05-12 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generatedresume",
            name="model_used",
        ),
    ]
