# Generated by Django 5.2 on 2025-05-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="resume",
        ),
        migrations.RemoveField(
            model_name="workexperience",
            name="resume",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="email",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="location",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="summary",
        ),
        migrations.AddField(
            model_name="resume",
            name="resume_file",
            field=models.FileField(blank=True, null=True, upload_to="resumes/"),
        ),
        migrations.DeleteModel(
            name="Education",
        ),
        migrations.DeleteModel(
            name="Skill",
        ),
        migrations.DeleteModel(
            name="WorkExperience",
        ),
    ]
