# Generated by Django 5.0 on 2025-07-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0002_remove_skill_resume_remove_workexperience_resume_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="certifications",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="resume",
            name="education",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="resume",
            name="languages",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="resume",
            name="projects",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="resume",
            name="skills",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="resume",
            name="work_experiences",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
