# Generated by Django 5.0 on 2025-07-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0003_resume_certifications_resume_education_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="personal_info",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
