# Generated by Django 5.1.3 on 2025-05-12 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional title for the job description (e.g., Software Engineer at Google)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True,
                        help_text="Original name of the uploaded file, if applicable.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "raw_text",
                    models.TextField(
                        help_text="Raw text extracted from the file or submitted by the user."
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_descriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
